version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kc-auth-db
    volumes:
      - ./postgres:/var/lib/postgresql/data